export const TOGGLE_EXAMPLE = 'TOGGLE_EXAMPLE';
export const NEXT_QUESTION = 'NEXT_QUESTION';

export const SAVE_PROGRESS = 'SAVE_PROGRESS';
export const SAVE_PROGRESS_REQUEST = 'SAVE_PROGRESS_REQUEST';
export const SAVE_PROGRESS_ERROR = 'SAVE_PROGRESS_ERROR';
export const SAVE_PROGRESS_SUCCESS = 'SAVE_PROGRESS_SUCCESS';

export const TOGGLE_SETTING = 'TOGGLE_SETTING';
export const TOGGLE_ROMAJI = 'TOGGLE_ROMAJI';
export const TOGGLE_HIRAGANA = 'TOGGLE_HIRAGANA';
export const TOGGLE_KATAKANA = 'TOGGLE_KATAKANA';


export const FETCH_QUESTION = 'FETCH_QUESTION';
export const FETCH_QUESTION_REQUEST = 'FETCH_QUESTION_REQUEST';
export const FETCH_QUESTION_ERROR = 'FETCH_QUESTION_ERROR';
export const FETCH_QUESTION_SUCCESS = 'FETCH_QUESTION_SUCCESS';