export const TOGGLE_EXAMPLE = 'TOGGLE_EXAMPLE';

export const TOGGLE_SETTING = 'TOGGLE_SETTING';
export const TOGGLE_ROMAJI = 'TOGGLE_ROMAJI';
export const TOGGLE_HIRAGANA = 'TOGGLE_HIRAGANA';
export const TOGGLE_KATAKANA = 'TOGGLE_KATAKANA';

export const ATTACH_QUESTIONS = 'ATTACH_QUESTIONS';
export const SELECT_ANSWER = 'SELECT_ANSWER';
export const EVALUATE_ANSWER = 'EVALUATE_ANSWER';

export const NEXT_QUESTION = 'NEXT_QUESTION';
export const NEXT_QUESTION_SUCCESS = 'NEXT_QUESTION_SUCCESS';
export const NEXT_QUESTION_REQUEST = 'NEXT_QUESTION_REQUEST';
export const NEXT_QUESTION_ERROR = 'NEXT_QUESTION_ERROR';